-- =====================================================
-- MIGRATION: Storage RLS Policies
-- Date: 2026-02-14
-- Description: Secure Supabase Storage bucket 'vehicles' with RLS policies
-- Dependencies: Storage bucket 'vehicles' must exist
-- =====================================================
-- IMPORTANT: This migration configures RLS for Supabase Storage.
-- Execute this AFTER creating the 'vehicles' bucket in Supabase UI.
-- =====================================================

BEGIN;

-- ===================
-- 1. ENABLE RLS ON STORAGE.OBJECTS
-- ===================
-- Note: Storage RLS is global, not per-bucket

ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- ===================
-- 2. DROP EXISTING POLICIES (IDEMPOTENT)
-- ===================

DROP POLICY IF EXISTS "authenticated_upload_vehicles" ON storage.objects;
DROP POLICY IF EXISTS "authenticated_read_vehicles" ON storage.objects;
DROP POLICY IF EXISTS "public_read_vehicles" ON storage.objects;
DROP POLICY IF EXISTS "authenticated_delete_vehicles" ON storage.objects;
DROP POLICY IF EXISTS "authenticated_update_vehicles" ON storage.objects;

-- ===================
-- 3. UPLOAD POLICY (Authenticated Only)
-- ===================
-- Authenticated users can upload to any vehicle folder
-- Path structure: {vehicleId}/{timestamp}_{index}.{ext}

CREATE POLICY "authenticated_upload_vehicles"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'vehicles'
);

-- ===================
-- 4. READ POLICY (Public + Authenticated)
-- ===================
-- Public users can view images (for showroom)
-- Authenticated users have full read access

CREATE POLICY "public_read_vehicles"
ON storage.objects
FOR SELECT
TO public
USING (bucket_id = 'vehicles');

-- Note: 'public' role includes both 'anon' and 'authenticated'
-- Separate policies not needed for read access

-- ===================
-- 5. UPDATE POLICY (Authenticated Only)
-- ===================
-- Authenticated users can update metadata on vehicle images

CREATE POLICY "authenticated_update_vehicles"
ON storage.objects
FOR UPDATE
TO authenticated
USING (bucket_id = 'vehicles')
WITH CHECK (bucket_id = 'vehicles');

-- ===================
-- 6. DELETE POLICY (Authenticated Only)
-- ===================
-- Authenticated users can delete any vehicle image
-- (No per-user restriction since all images belong to the business)

CREATE POLICY "authenticated_delete_vehicles"
ON storage.objects
FOR DELETE
TO authenticated
USING (bucket_id = 'vehicles');

-- ===================
-- 7. BUCKET CONFIGURATION NOTES
-- ===================
-- Execute the following in Supabase Storage UI:
--
-- 1. Create bucket 'vehicles' if not exists:
--    - Name: vehicles
--    - Public: false (RLS will handle access)
--    - File size limit: 10MB (recommended)
--    - Allowed MIME types: image/jpeg, image/png, image/webp
--
-- 2. Configure CORS (if needed for client uploads):
--    - Allow origins: https://yourdomain.com
--    - Allow methods: GET, POST, PUT, DELETE
--
-- 3. Enable RLS on bucket (checkbox in UI)

COMMIT;

-- =====================================================
-- SECURITY NOTES
-- =====================================================
--
-- PUBLIC ACCESS JUSTIFICATION:
-- - Vehicle images are displayed on public showroom pages
-- - No sensitive data in file names (only UUIDs + timestamps)
-- - Path structure prevents enumeration attacks:
--   Example: 123e4567-e89b-12d3-a456-426614174000/1707912345000_0.jpg
--
-- UPLOAD RESTRICTIONS:
-- - Only authenticated users can upload (admin CRM access)
-- - Path is auto-generated by client.js uploadImage() function
-- - Validates vehicleId exists before upload (client-side)
--
-- DELETE RESTRICTIONS:
-- - Only authenticated users can delete
-- - No per-user ownership (all images belong to business)
-- - Deletion triggers cascade from vehicles.images JSONB array
--
-- =====================================================
-- END MIGRATION
-- =====================================================
